[package]
name = "axum-hello-world"
version = "0.1.0"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres" ] }
