services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces/axum-hello-world:cached

    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Add user mapping to ensure correct permissions
    user: vscode

    env_file:
      - .env

  db:
    image: postgres:17.2
    restart: unless-stopped
    volumes:
      - postgres-data-rust:/var/lib/postgresql/data

    env_file:
      - .env

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data-rust:
